### ISSUE TITLE
Implement the Database

### ISSUE THREAD

**Issue by lombardero** [nyu-devops-fall19-wishlists/wishlists#18]
**As a** developer
**I need** a Database
**So that** I can store the data I need

**Assumptions:** 
* We will use MySql (to be confirmed)

**Acceptance Criteria:**
```
Given any call to the Database
When the functions Create, Read, Update, and Delete 
Then the data should be successfully stored in the Database
```

**Comment by sflechas** [comment]
Script to create db is attached.  Looking for the option to save it as part of the vagrant image.

[wishlists.sql.zip](https://github.com/nyu-devops-fall19-wishlists/wishlists/files/3693936/wishlists.sql.zip)

**Comment by nisargthakkar** [comment]
Can you send this in a PR without the compression? You could put it in some folder like sql or leave it outside in the main folder as well. Then we can update the Vagrant file to setup the schema on the mysql instance.

**Comment by sflechas** [comment]
I wanted to save some progress on the issue that is why I uploaded the file. It did not let me save the .sql file without the compression, so that is why I had to upload the zip file.  Plus, It needs to be integrated as part of the vagrant file so that we all have it on our development environments.

I will take care of updating the vagrant file with the mysql instance.
